### ISSUE TITLE
License

### ISSUE THREAD

**Issue by n8225** [nearbycoder/materialpoll#1]
What license is your project released under?

**Comment by nearbycoder** [comment]
@n8225 never thought about it but feel free to use the project as you wish. No need to mention where you got it from.

**Comment by n8225** [comment]
I guess I should have explained my intent further.  I am updating materialpoll's listing on https://github.com/Kickball/awesome-selfhosted We are trying to ensure every project listed has a licensed listed.

**Comment by nearbycoder** [comment]
Okay cool! I added an MIT license to the project.

**Comment by n8225** [comment]
Thanks

**Comment by nearbycoder** [comment]
No problem!
